# Generated by Django 5.2.17 on 2026-08-24 01:15

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0003_remove_journalentry_ledger_expense_category_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit card"),
                            ("auto_loan", "Auto loan"),
                            ("student_loan", "Student loan"),
                            ("mortgage", "Mortgage"),
                            ("personal_loan", "Personal loan"),
                            ("medical", "Medical debt"),
                            ("other", "Other debt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_balance", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid_off", "Paid off"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_on", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_debt_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "financial_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_account",
                        to="ledger.financialaccount",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_accounts",
                        to="households.household",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_debt_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("status", "name"),
            },
        ),
        migrations.CreateModel(
            name="DebtStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("statement_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("statement_balance", models.DecimalField(decimal_places=2, max_digits=18)),
                ("annual_percentage_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                ("minimum_payment", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "interest_charged",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "fees_charged",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "escrow_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "pmi_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "extra_principal_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_debt_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to="debts.debtaccount",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="debts.debtstatement",
                    ),
                ),
            ],
            options={
                "ordering": ("-statement_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DebtTermsRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("annual_percentage_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "interest_method",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly APR / 12"),
                            ("daily", "Daily simple interest"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                (
                    "day_count_basis",
                    models.CharField(
                        choices=[("actual_365", "Actual / 365"), ("actual_360", "Actual / 360")],
                        default="actual_365",
                        max_length=12,
                    ),
                ),
                ("minimum_payment", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "recurring_extra_payment",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("due_day", models.PositiveSmallIntegerField()),
                ("custom_priority", models.PositiveSmallIntegerField(default=100)),
                ("projection_notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_debt_terms_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms_revisions",
                        to="debts.debtaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("debt_id", "revision_number"),
            },
        ),
        migrations.AddConstraint(
            model_name="debtaccount",
            constraint=models.UniqueConstraint(
                models.F("household"),
                django.db.models.functions.text.Lower("name"),
                name="debts_account_hh_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_balance__gte", Decimal("0"))),
                name="debts_account_balance_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), ("status_changed_at__isnull", True)),
                    models.Q(
                        models.Q(("status", "active"), _negated=True),
                        ("status_changed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="debts_account_status_timestamp_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "paid_off"), _negated=True),
                    ("current_balance", Decimal("0")),
                    _connector="OR",
                ),
                name="debts_paid_off_balance_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="debtstatement",
            index=models.Index(fields=["debt", "statement_date"], name="debts_statement_debt_date"),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(("statement_balance__gte", Decimal("0"))),
                name="debts_statement_balance_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_percentage_rate__gte", Decimal("0")),
                    ("annual_percentage_rate__lt", Decimal("1000")),
                ),
                name="debts_statement_apr_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_payment__gte", Decimal("0"))),
                name="debts_statement_minimum_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("principal_paid__gte", Decimal("0")),
                    ("interest_charged__gte", Decimal("0")),
                    ("fees_charged__gte", Decimal("0")),
                    ("escrow_paid__gte", Decimal("0")),
                    ("pmi_paid__gte", Decimal("0")),
                    ("extra_principal_paid__gte", Decimal("0")),
                ),
                name="debts_statement_components_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("period_end__isnull", True), ("period_start__isnull", True)),
                    models.Q(
                        ("period_end__isnull", False),
                        ("period_start__isnull", False),
                        ("period_end__gte", models.F("period_start")),
                    ),
                    _connector="OR",
                ),
                name="debts_statement_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("statement_date")),
                    _connector="OR",
                ),
                name="debts_statement_due_date_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtstatement",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("supersedes")), _negated=True),
                name="debts_statement_not_self_superseding",
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.UniqueConstraint(
                fields=("debt", "revision_number"), name="debts_terms_debt_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.UniqueConstraint(
                fields=("debt", "effective_from"), name="debts_terms_debt_effective_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_percentage_rate__gte", Decimal("0")),
                    ("annual_percentage_rate__lt", Decimal("1000")),
                ),
                name="debts_terms_apr_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_payment__gte", Decimal("0"))),
                name="debts_terms_minimum_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("recurring_extra_payment__gte", Decimal("0"))),
                name="debts_terms_extra_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_day__gte", 1), ("due_day__lte", 31)),
                name="debts_terms_due_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="debttermsrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("custom_priority__gte", 1)),
                name="debts_terms_priority_positive",
            ),
        ),
    ]
