# Generated by Django 5.2.17 on 2026-08-24 02:23

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0002_postgresql_protect_history"),
        ("schedules", "0004_expensesourcedetail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MortgagePaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_mortgage_payment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortgage_payment_plan",
                        to="debts.debtaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MortgagePlanRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("monthly_obligation", models.DecimalField(decimal_places=2, max_digits=18)),
                ("statement_cycle_day", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_mortgage_plan_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="debts.mortgagepaymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_id", "revision_number"),
            },
        ),
        migrations.CreateModel(
            name="MortgagePaymentComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("principal_interest", "Principal and interest"),
                            ("escrow", "Escrow"),
                            ("pmi", "PMI"),
                            ("fees", "Fees"),
                            ("recurring_extra_principal", "Recurring extra principal"),
                        ],
                        max_length=28,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_mortgage_payment_components",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="debts.mortgageplanrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_revision_id", "component_type"),
            },
        ),
        migrations.CreateModel(
            name="MortgageInstallmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installment_order", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("day_of_month", models.PositiveSmallIntegerField()),
                (
                    "adjustment_policy",
                    models.CharField(
                        choices=[("none", "None"), ("previous", "Previous"), ("next", "Next")],
                        default="previous",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_mortgage_installment_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortgage_installment_rules",
                        to="schedules.recurringsource",
                    ),
                ),
                (
                    "plan_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_rules",
                        to="debts.mortgageplanrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_revision_id", "installment_order"),
            },
        ),
        migrations.AddConstraint(
            model_name="mortgageplanrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision_number"), name="debts_mortgage_plan_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageplanrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "effective_from"), name="debts_mortgage_plan_effective_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageplanrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_obligation__gt", Decimal("0"))),
                name="debts_mortgage_obligation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageplanrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("statement_cycle_day__gte", 1), ("statement_cycle_day__lte", 31)
                ),
                name="debts_mortgage_cycle_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgagepaymentcomponent",
            constraint=models.UniqueConstraint(
                fields=("plan_revision", "component_type"),
                name="debts_mortgage_component_type_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgagepaymentcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0"))),
                name="debts_mortgage_component_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageinstallmentrule",
            constraint=models.UniqueConstraint(
                fields=("plan_revision", "installment_order"),
                name="debts_mortgage_installment_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageinstallmentrule",
            constraint=models.UniqueConstraint(
                fields=("plan_revision", "source"), name="debts_mortgage_installment_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageinstallmentrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("installment_order__gte", 1), ("installment_order__lte", 2)),
                name="debts_mortgage_installment_order_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageinstallmentrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0"))),
                name="debts_mortgage_installment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mortgageinstallmentrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="debts_mortgage_installment_day_valid",
            ),
        ),
    ]
