# Generated by Django 5.2.17 on 2026-10-07 02:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0004_postgresql_protect_mortgage_history"),
        ("households", "0003_category"),
        ("periods", "0002_postgresql_period_guards"),
        ("schedules", "0005_income_revision_replacements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtPayoffPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("avalanche", "Avalanche — highest APR first"),
                            ("snowball", "Snowball — smallest balance first"),
                            ("custom", "Custom debt priority"),
                        ],
                        max_length=16,
                    ),
                ),
                ("extra_per_period", models.DecimalField(decimal_places=2, max_digits=18)),
                ("cash_cushion", models.DecimalField(decimal_places=2, max_digits=18)),
                ("forecast", models.JSONField(default=dict)),
                ("snapshot_fingerprint", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payoff_plans",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("household_id", "-revision_number"),
            },
        ),
        migrations.CreateModel(
            name="DebtPayoffAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payoff_allocations",
                        to="debts.debtaccount",
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="schedules.occurrence"
                    ),
                ),
                (
                    "pay_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payoff_allocation",
                        to="periods.payperiod",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="debts.debtpayoffplan",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="debtpayoffplan",
            constraint=models.UniqueConstraint(
                fields=("household", "revision_number"), name="debts_payoff_plan_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="debtpayoffplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("extra_per_period__gte", 0)),
                name="debts_payoff_extra_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtpayoffplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("cash_cushion__gte", 0)),
                name="debts_payoff_cushion_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtpayoffallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="debts_payoff_allocation_positive"
            ),
        ),
    ]
