# Generated by Django 5.2.17 on 2026-10-07 03:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0006_postgresql_protect_payoff_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtPromotionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("none", "No promotion / end tracking"),
                            ("introductory", "Temporary promotional APR"),
                            ("deferred", "Deferred interest if not paid in full"),
                        ],
                        max_length=16,
                    ),
                ),
                ("as_of", models.DateField()),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "promotional_apr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                (
                    "regular_apr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                (
                    "accrued_interest",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_revisions",
                        to="debts.debtaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("debt_id", "-revision_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("debt", "revision_number"), name="debts_promotion_revision_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_on__isnull", True),
                            ("expires_on__gte", models.F("as_of")),
                            _connector="OR",
                        ),
                        name="debts_promotion_date_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("promotional_apr__isnull", True),
                            models.Q(("promotional_apr__gte", 0), ("promotional_apr__lt", 1000)),
                            _connector="OR",
                        ),
                        name="debts_promotion_apr_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("regular_apr__isnull", True),
                            models.Q(("regular_apr__gte", 0), ("regular_apr__lt", 1000)),
                            _connector="OR",
                        ),
                        name="debts_promotion_regular_apr_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("accrued_interest__isnull", True),
                            ("accrued_interest__gte", 0),
                            _connector="OR",
                        ),
                        name="debts_promotion_interest_nonnegative",
                    ),
                ],
            },
        ),
    ]
