# Generated by Django 5.2.17 on 2026-08-24 03:26

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("debts", "0004_postgresql_protect_mortgage_history"),
        ("households", "0003_category"),
        ("ledger", "0003_remove_journalentry_ledger_expense_category_required_and_more"),
        ("periods", "0002_postgresql_period_guards"),
        (
            "reserves",
            "0005_remove_cardpaymentreserveentry_reserves_card_amounts_nonnegative_and_more",
        ),
        ("schedules", "0004_expensesourcedetail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "opening_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goals",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("reserve", "Reserve allocation"),
                            ("automatic", "Priority reserve allocation"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("effective_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_goal_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="goals.goal",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_progress_contribution",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_contribution",
                        to="schedules.occurrence",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_contributions",
                        to="periods.payperiod",
                    ),
                ),
                (
                    "reserve_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_contribution",
                        to="reserves.reserveentry",
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="GoalFundingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_goal_funding_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funding_plan",
                        to="goals.goal",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_funding_plan",
                        to="schedules.recurringsource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoalRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("name", models.CharField(max_length=120)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("debt_payoff", "Debt payoff"),
                            ("investing", "Investing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "contribution_per_period",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("automatic_excess_allocation", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_goal_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_destination_revisions",
                        to="ledger.financialaccount",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="goals.goal",
                    ),
                ),
                (
                    "linked_debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_revisions",
                        to="debts.debtaccount",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_source_revisions",
                        to="ledger.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("goal_id", "revision_number"),
            },
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_amount__gte", Decimal("0.00"))),
                name="goals_opening_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="goals_contribution_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contribution_type__in", ("reserve", "automatic")),
                        ("reserve_entry__isnull", False),
                    ),
                    models.Q(
                        ("contribution_type__in", ("manual", "scheduled")),
                        ("reserve_entry__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="goals_contribution_reserve_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contribution_type", "scheduled"), ("occurrence__isnull", False)),
                    models.Q(("contribution_type", "scheduled"), _negated=True),
                    _connector="OR",
                ),
                name="goals_scheduled_occurrence_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.UniqueConstraint(
                fields=("goal", "revision_number"), name="goals_revision_goal_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.UniqueConstraint(
                fields=("goal", "effective_from"), name="goals_revision_goal_effective_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", Decimal("0.00"))),
                name="goals_revision_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("contribution_per_period__gte", Decimal("0.00"))),
                name="goals_revision_contribution_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gt", 0)), name="goals_revision_priority_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_date__isnull", True),
                    ("target_date__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="goals_revision_target_date_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="goalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destination_account__isnull", True),
                        ("goal_type", "debt_payoff"),
                        ("linked_debt__isnull", False),
                    ),
                    models.Q(
                        ("destination_account__isnull", False),
                        ("goal_type__in", ("savings", "investing")),
                        ("linked_debt__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="goals_revision_destination_valid",
            ),
        ),
    ]
