# Generated by Django 5.2.17 on 2026-08-23 02:36

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("cash", "Cash"),
                            ("credit_card", "Credit card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("asset", "Asset"), ("liability", "Liability")], max_length=12
                    ),
                ),
                (
                    "last_four",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{4}$", "Enter exactly four digits."
                            )
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("archived_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("observed_balance", models.DecimalField(decimal_places=2, max_digits=18)),
                ("observed_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("integration", "Future integration")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_balance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_snapshots",
                        to="households.household",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_snapshots",
                        to="ledger.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense or purchase"),
                            ("transfer", "Account transfer"),
                            ("debt_payment", "Debt payment"),
                            ("goal_contribution", "Goal contribution"),
                            ("interest_fee", "Interest or fee"),
                            ("balance_adjustment", "Balance adjustment"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("imported", "Imported"),
                            ("system", "System"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("receipt_reference", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, max_length=64)),
                ("committed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="households.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="households.household",
                    ),
                ),
                (
                    "replacement_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_entries",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_entry",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="JournalPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "internal_account",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("adjustment", "Balance adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter currency code."
                            )
                        ],
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postings",
                        to="ledger.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("entry_id", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(
                models.F("household"),
                django.db.models.functions.text.Lower("name"),
                name="ledger_account_hh_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("account_type__in", ("checking", "savings", "cash")),
                        ("classification", "asset"),
                    ),
                    models.Q(("account_type", "credit_card"), ("classification", "liability")),
                    ("account_type", "other"),
                    _connector="OR",
                ),
                name="ledger_account_type_class_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["financial_account", "observed_at"], name="ledger_snapshot_account_time"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["household", "effective_at"], name="ledger_entry_hh_effective"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["household", "entry_type"], name="ledger_entry_hh_type"),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("description", ""), _negated=True),
                name="ledger_entry_description_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", False),
                    models.Q(("entry_type", "expense"), _negated=True),
                    _connector="OR",
                ),
                name="ledger_expense_category_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", True), ("entry_type", "expense"), _connector="OR"
                ),
                name="ledger_category_only_for_expense",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("reversal_of")), _negated=True),
                name="ledger_entry_not_self_reversal",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("household", "idempotency_key"),
                name="ledger_entry_hh_idempotency_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="journalposting",
            index=models.Index(
                fields=["financial_account", "entry"], name="ledger_posting_account_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0"))),
                name="ledger_posting_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalposting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("financial_account__isnull", False), ("internal_account", "")),
                    models.Q(
                        ("financial_account__isnull", True),
                        models.Q(("internal_account", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ledger_posting_exactly_one_account",
            ),
        ),
    ]
