# Generated by Django 5.2.17 on 2026-08-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0002_postgresql_protect_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="ledger_expense_category_required",
        ),
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="ledger_category_only_for_expense",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="adjustment_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustment_entries",
                to="ledger.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense or purchase"),
                    ("expense_refund", "Expense refund"),
                    ("transfer", "Account transfer"),
                    ("debt_payment", "Debt payment"),
                    ("goal_contribution", "Goal contribution"),
                    ("interest_fee", "Interest or fee"),
                    ("balance_adjustment", "Balance adjustment"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", False),
                    models.Q(("entry_type__in", ("expense", "expense_refund")), _negated=True),
                    _connector="OR",
                ),
                name="ledger_expense_category_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", True),
                    ("entry_type__in", ("expense", "expense_refund")),
                    _connector="OR",
                ),
                name="ledger_category_only_for_expense",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("adjustment_for")), _negated=True),
                name="ledger_entry_not_self_adjustment",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("adjustment_for__isnull", False), ("entry_type", "expense_refund")),
                    models.Q(
                        models.Q(("entry_type", "expense_refund"), _negated=True),
                        ("adjustment_for__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ledger_refund_adjustment_required",
            ),
        ),
    ]
