# Generated by Django 5.2.17 on 2026-09-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_remove_journalentry_ledger_expense_category_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=71),
        ),
    ]
