# Generated by Django 5.2.17 on 2026-08-22 22:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_loginthrottle_user_display_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MfaCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("encrypted_secret", models.TextField(editable=False)),
                ("key_version", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("confirmed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "recovery_codes_confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("last_used_step", models.BigIntegerField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(editable=False, max_length=8, unique=True)),
                ("code_hash", models.CharField(editable=False, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="recovery_code_user_state")
                ],
            },
        ),
    ]
