# Generated by Django 5.2.17 on 2026-10-03 04:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_applicationthrottle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("credential_id", models.CharField(editable=False, max_length=1024, unique=True)),
                ("public_key", models.BinaryField(max_length=2048)),
                ("sign_count", models.PositiveBigIntegerField(default=0, editable=False)),
                ("device_type", models.CharField(editable=False, max_length=32)),
                ("backed_up", models.BooleanField(default=False, editable=False)),
                ("transports", models.JSONField(default=list, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="identity_passkey_user_name_unique"
                    )
                ],
            },
        ),
    ]
