# Generated by Django 5.2.17 on 2026-08-23 03:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("projected", "Projected"),
                            ("open", "Open"),
                            ("closing_review", "Closing review"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        default="projected",
                        max_length=20,
                    ),
                ),
                (
                    "boundary_source",
                    models.CharField(
                        choices=[
                            ("expected", "Expected anchor schedule"),
                            ("actual", "Confirmed actual paycheck"),
                        ],
                        default="expected",
                        max_length=12,
                    ),
                ),
                ("boundary_revision", models.PositiveIntegerField(default=1)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pay_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_periods",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="PayPeriodClosingRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("closing_surplus", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reserve_delta", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_period_closing_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closing_revisions",
                        to="periods.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("pay_period_id", "revision_number"),
            },
        ),
        migrations.AddIndex(
            model_name="payperiod",
            index=models.Index(fields=["household", "status"], name="periods_period_hh_status"),
        ),
        migrations.AddConstraint(
            model_name="payperiod",
            constraint=models.UniqueConstraint(
                fields=("household", "start_date"), name="periods_period_hh_start_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_start_date__gt", models.F("start_date"))),
                name="periods_period_positive_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="payperiodclosingrevision",
            constraint=models.UniqueConstraint(
                fields=("pay_period", "revision_number"),
                name="periods_closing_period_revision_unique",
            ),
        ),
    ]
