# Generated by Django 5.2.17 on 2026-08-23 18:14

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0003_remove_journalentry_ledger_expense_category_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_checksum", models.CharField(max_length=64)),
                (
                    "submission_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("previewed", "Previewed"),
                            ("committed", "Committed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("headers", models.JSONField(default=list)),
                ("mapping", models.JSONField(default=dict)),
                ("staged_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("category_required_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("committed_count", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("previewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="households.household",
                    ),
                ),
                (
                    "target_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="ledger.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("ready", "Ready"),
                            ("duplicate", "Duplicate"),
                            ("category_required", "Category required"),
                            ("rejected", "Rejected"),
                            ("committed", "Committed"),
                        ],
                        default="staged",
                        max_length=24,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_rows",
                        to="households.category",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_row",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number",),
            },
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "abandoned"), _negated=True),
                fields=("household", "target_account", "file_checksum"),
                name="imports_batch_file_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="imports_row_batch_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__isnull", True), ("amount__gt", Decimal("0.00")), _connector="OR"
                ),
                name="imports_row_amount_positive",
            ),
        ),
    ]
