# Generated by Django 5.2.17 on 2026-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importrow",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=71),
        ),
    ]
