# Generated by Django 5.2.17 on 2026-09-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0002_expand_row_fingerprint_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="file_checksum",
            field=models.CharField(max_length=71),
        ),
    ]
