worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 256;
}

http {
    access_log off;
    server_tokens off;
    map $http_x_forwarded_proto $upstream_forwarded_proto {
        default $http_x_forwarded_proto;
        "" http;
    }
    client_max_body_size 6m;
    client_header_timeout 15s;
    client_body_timeout 15s;
    client_body_temp_path /tmp/client-body;
    fastcgi_temp_path /tmp/fastcgi;
    keepalive_timeout 15s;
    proxy_connect_timeout 5s;
    proxy_read_timeout 65s;
    proxy_send_timeout 65s;
    proxy_temp_path /tmp/proxy;
    scgi_temp_path /tmp/scgi;
    send_timeout 30s;
    uwsgi_temp_path /tmp/uwsgi;

    server {
        listen 8000;
        server_name _;

        location / {
            proxy_pass https://web:8443;
            proxy_http_version 1.1;
            proxy_request_buffering on;
            proxy_ssl_certificate /run/secrets/nginx_client_certificate;
            proxy_ssl_certificate_key /run/secrets/nginx_client_private_key;
            proxy_ssl_name web;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
            proxy_ssl_server_name on;
            proxy_ssl_trusted_certificate /run/secrets/gunicorn_ca_certificate;
            proxy_ssl_verify on;
            proxy_ssl_verify_depth 1;
            proxy_set_header Connection "";
            proxy_set_header Forwarded "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-Host "";
            proxy_set_header X-Forwarded-Port "";
            proxy_set_header X-Forwarded-Proto $upstream_forwarded_proto;
            proxy_set_header X-Real-IP "";
        }
    }
}
