# Generated by Django 5.2.17 on 2026-08-22 21:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditHead",
            fields=[
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="audit_head",
                        serialize=False,
                        to="households.household",
                    ),
                ),
                ("last_sequence", models.PositiveBigIntegerField(default=0)),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                (
                    "chain_head",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("household_timezone", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=80)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(max_length=64)),
                ("before_payload", models.JSONField(default=dict)),
                ("after_payload", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("request_id", models.CharField(max_length=64)),
                ("previous_hash", models.CharField(max_length=64)),
                ("event_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("household_id", "sequence"),
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["household", "occurred_at"], name="audit_event_household_time"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "sequence"),
                        name="audit_event_household_sequence_unique",
                    )
                ],
            },
        ),
    ]
