# Generated by Django 5.2.17 on 2026-08-22 22:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_postgresql_protected_schema"),
        ("households", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_sequence", models.PositiveBigIntegerField()),
                ("event_count", models.PositiveBigIntegerField()),
                ("chain_head", models.CharField(max_length=64)),
                ("verified_at", models.DateTimeField()),
                ("signature_algorithm", models.CharField(max_length=32)),
                ("signing_key_id", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=64)),
                ("external_copy_name", models.CharField(max_length=255)),
                ("external_copied_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_checkpoints",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("-verified_at",),
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["household", "verified_at"], name="audit_checkpoint_hh_time"
                    )
                ],
            },
        ),
    ]
