# Generated by Django 5.2.17 on 2026-09-27 11:54

from django.db import migrations, models

FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION budget_audit.record_checkpoint(
    p_id uuid,
    p_household_id uuid,
    p_last_sequence bigint,
    p_event_count bigint,
    p_chain_head varchar,
    p_verified_at timestamp with time zone,
    p_signature_algorithm varchar,
    p_signing_key_id varchar,
    p_signature varchar,
    p_external_copy_name varchar,
    p_external_copied_at timestamp with time zone
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $function$
DECLARE
    v_last_sequence bigint;
    v_event_count bigint;
    v_chain_head varchar;
BEGIN
    IF NOT (
           (p_signature_algorithm = 'HMAC-SHA256' AND p_signature ~ '^[0-9a-f]{64}$')
        OR (p_signature_algorithm = 'HMAC-SHA512' AND p_signature ~ '^[0-9a-f]{128}$')
       )
       OR p_signing_key_id !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
       OR p_external_copy_name !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$' THEN
        RAISE EXCEPTION 'invalid audit checkpoint parameters' USING ERRCODE = '22023';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtextextended(p_household_id::text, 0));
    SELECT last_sequence, event_count, chain_head
      INTO v_last_sequence, v_event_count, v_chain_head
      FROM budget_audit.audit_audithead
     WHERE household_id = p_household_id
     FOR UPDATE;

    IF NOT FOUND
       OR p_last_sequence <> v_last_sequence
       OR p_event_count <> v_event_count
       OR p_chain_head <> v_chain_head THEN
        RAISE EXCEPTION 'checkpoint does not match the protected audit head'
            USING ERRCODE = '23514';
    END IF;

    INSERT INTO budget_audit.audit_auditcheckpoint (
        id, household_id, last_sequence, event_count, chain_head, verified_at,
        signature_algorithm, signing_key_id, signature, external_copy_name,
        external_copied_at, created_at
    ) VALUES (
        p_id, p_household_id, p_last_sequence, p_event_count, p_chain_head, p_verified_at,
        p_signature_algorithm, p_signing_key_id, p_signature, p_external_copy_name,
        p_external_copied_at, p_verified_at
    );

    UPDATE budget_audit.audit_audithead
       SET verified_at = p_verified_at,
           updated_at = p_verified_at
     WHERE household_id = p_household_id;
END
$function$;
ALTER FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) OWNER TO budget_audit_owner;
REVOKE ALL ON FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) TO budget_audit_reader;
"""

LEGACY_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION budget_audit.record_checkpoint(
    p_id uuid, p_household_id uuid, p_last_sequence bigint, p_event_count bigint,
    p_chain_head varchar, p_verified_at timestamp with time zone,
    p_signature_algorithm varchar, p_signing_key_id varchar, p_signature varchar,
    p_external_copy_name varchar, p_external_copied_at timestamp with time zone
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $function$
DECLARE
    v_last_sequence bigint;
    v_event_count bigint;
    v_chain_head varchar;
BEGIN
    IF p_signature_algorithm <> 'HMAC-SHA256'
       OR p_signature !~ '^[0-9a-f]{64}$'
       OR p_signing_key_id !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
       OR p_external_copy_name !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$' THEN
        RAISE EXCEPTION 'invalid audit checkpoint parameters' USING ERRCODE = '22023';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(p_household_id::text, 0));
    SELECT last_sequence, event_count, chain_head
      INTO v_last_sequence, v_event_count, v_chain_head
      FROM budget_audit.audit_audithead
     WHERE household_id = p_household_id
     FOR UPDATE;
    IF NOT FOUND
       OR p_last_sequence <> v_last_sequence
       OR p_event_count <> v_event_count
       OR p_chain_head <> v_chain_head THEN
        RAISE EXCEPTION 'checkpoint does not match the protected audit head'
            USING ERRCODE = '23514';
    END IF;
    INSERT INTO budget_audit.audit_auditcheckpoint (
        id, household_id, last_sequence, event_count, chain_head, verified_at,
        signature_algorithm, signing_key_id, signature, external_copy_name,
        external_copied_at, created_at
    ) VALUES (
        p_id, p_household_id, p_last_sequence, p_event_count, p_chain_head, p_verified_at,
        p_signature_algorithm, p_signing_key_id, p_signature, p_external_copy_name,
        p_external_copied_at, p_verified_at
    );
    UPDATE budget_audit.audit_audithead
       SET verified_at = p_verified_at, updated_at = p_verified_at
     WHERE household_id = p_household_id;
END
$function$;
ALTER FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) OWNER TO budget_audit_owner;
REVOKE ALL ON FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION budget_audit.record_checkpoint(
    uuid, uuid, bigint, bigint, varchar, timestamp with time zone, varchar,
    varchar, varchar, varchar, timestamp with time zone
) TO budget_audit_reader;
"""


def enable_checkpoint_mac_profiles(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE budget_audit.audit_auditcheckpoint "
            "ALTER COLUMN signature TYPE varchar(128)"
        )
        schema_editor.execute(FUNCTION_SQL)


def disable_checkpoint_mac_profiles(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(LEGACY_FUNCTION_SQL)
        schema_editor.execute(
            "ALTER TABLE budget_audit.audit_auditcheckpoint ALTER COLUMN signature TYPE varchar(64)"
        )


class Migration(migrations.Migration):
    dependencies = [("audit", "0004_postgresql_protect_checkpoints")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    enable_checkpoint_mac_profiles,
                    disable_checkpoint_mac_profiles,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="auditcheckpoint",
                    name="signature",
                    field=models.CharField(max_length=128),
                )
            ],
        )
    ]
