# Generated by Django 5.2.17 on 2026-09-28 18:14

from django.db import migrations, models

CURRENT_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION budget_audit.append_event(
    p_sequence bigint, p_id uuid, p_household_id uuid, p_actor_id uuid,
    p_occurred_at timestamp with time zone, p_household_timezone varchar,
    p_action varchar, p_entity_type varchar, p_entity_id varchar,
    p_before_payload jsonb, p_after_payload jsonb, p_reason varchar,
    p_request_id varchar, p_previous_hash varchar, p_event_hash varchar
)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $function$
DECLARE
    v_last_sequence bigint;
    v_chain_head varchar;
BEGIN
    IF p_sequence < 1
       OR p_previous_hash !~ '^(sha256\$[0-9a-f]{64}|[0-9a-f]{64})$'
       OR p_event_hash !~ '^sha256\$[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'invalid audit append parameters' USING ERRCODE = '22023';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(p_household_id::text, 0));
    SELECT last_sequence, chain_head INTO v_last_sequence, v_chain_head
      FROM budget_audit.audit_audithead
     WHERE household_id = p_household_id FOR UPDATE;
    IF NOT FOUND THEN
        IF p_sequence <> 1 OR p_previous_hash <> 'sha256$0000000000000000000000000000000000000000000000000000000000000000' THEN
            RAISE EXCEPTION 'audit chain does not start at the expected boundary'
                USING ERRCODE = '23514';
        END IF;
    ELSIF p_sequence <> v_last_sequence + 1 OR p_previous_hash <> v_chain_head THEN
        RAISE EXCEPTION 'audit append does not match the protected chain head'
            USING ERRCODE = '23514';
    END IF;
    INSERT INTO budget_audit.audit_auditevent (
        sequence, id, household_id, actor_id, occurred_at, household_timezone,
        action, entity_type, entity_id, before_payload, after_payload, reason,
        request_id, previous_hash, event_hash
    ) VALUES (
        p_sequence, p_id, p_household_id, p_actor_id, p_occurred_at, p_household_timezone,
        p_action, p_entity_type, p_entity_id, p_before_payload, p_after_payload, p_reason,
        p_request_id, p_previous_hash, p_event_hash
    );
    INSERT INTO budget_audit.audit_audithead (
        household_id, last_sequence, event_count, chain_head, verified_at, updated_at
    ) VALUES (p_household_id, p_sequence, 1, p_event_hash, NULL, p_occurred_at)
    ON CONFLICT (household_id) DO UPDATE SET
        last_sequence = EXCLUDED.last_sequence,
        event_count = budget_audit.audit_audithead.event_count + 1,
        chain_head = EXCLUDED.chain_head,
        verified_at = NULL,
        updated_at = EXCLUDED.updated_at;
END
$function$;
ALTER FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) OWNER TO budget_audit_owner;
REVOKE ALL ON FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) TO budget_runtime_access;
"""

LEGACY_FUNCTION_SQL = r"""
CREATE OR REPLACE FUNCTION budget_audit.append_event(
    p_sequence bigint, p_id uuid, p_household_id uuid, p_actor_id uuid,
    p_occurred_at timestamp with time zone, p_household_timezone varchar,
    p_action varchar, p_entity_type varchar, p_entity_id varchar,
    p_before_payload jsonb, p_after_payload jsonb, p_reason varchar,
    p_request_id varchar, p_previous_hash varchar, p_event_hash varchar
)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $function$
DECLARE
    v_last_sequence bigint;
    v_chain_head varchar;
BEGIN
    IF p_sequence < 1
       OR p_previous_hash !~ '^[0-9a-f]{64}$'
       OR p_event_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'invalid audit append parameters' USING ERRCODE = '22023';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(p_household_id::text, 0));
    SELECT last_sequence, chain_head INTO v_last_sequence, v_chain_head
      FROM budget_audit.audit_audithead
     WHERE household_id = p_household_id FOR UPDATE;
    IF NOT FOUND THEN
        IF p_sequence <> 1 OR p_previous_hash <> '0000000000000000000000000000000000000000000000000000000000000000' THEN
            RAISE EXCEPTION 'audit chain does not start at the expected boundary'
                USING ERRCODE = '23514';
        END IF;
    ELSIF p_sequence <> v_last_sequence + 1 OR p_previous_hash <> v_chain_head THEN
        RAISE EXCEPTION 'audit append does not match the protected chain head'
            USING ERRCODE = '23514';
    END IF;
    INSERT INTO budget_audit.audit_auditevent (
        sequence, id, household_id, actor_id, occurred_at, household_timezone,
        action, entity_type, entity_id, before_payload, after_payload, reason,
        request_id, previous_hash, event_hash
    ) VALUES (
        p_sequence, p_id, p_household_id, p_actor_id, p_occurred_at, p_household_timezone,
        p_action, p_entity_type, p_entity_id, p_before_payload, p_after_payload, p_reason,
        p_request_id, p_previous_hash, p_event_hash
    );
    INSERT INTO budget_audit.audit_audithead (
        household_id, last_sequence, event_count, chain_head, verified_at, updated_at
    ) VALUES (p_household_id, p_sequence, 1, p_event_hash, NULL, p_occurred_at)
    ON CONFLICT (household_id) DO UPDATE SET
        last_sequence = EXCLUDED.last_sequence,
        event_count = budget_audit.audit_audithead.event_count + 1,
        chain_head = EXCLUDED.chain_head,
        verified_at = NULL,
        updated_at = EXCLUDED.updated_at;
END
$function$;
ALTER FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) OWNER TO budget_audit_owner;
REVOKE ALL ON FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION budget_audit.append_event(
    bigint, uuid, uuid, uuid, timestamp with time zone, varchar, varchar, varchar,
    varchar, jsonb, jsonb, varchar, varchar, varchar, varchar
) TO budget_runtime_access;
"""


def enable_audit_event_hash_profiles(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditcheckpoint ALTER COLUMN chain_head TYPE varchar(71)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditevent ALTER COLUMN event_hash TYPE varchar(71)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditevent ALTER COLUMN previous_hash TYPE varchar(71)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_audithead ALTER COLUMN chain_head TYPE varchar(71)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_audithead ALTER COLUMN chain_head "
        "SET DEFAULT 'sha256$0000000000000000000000000000000000000000000000000000000000000000'"
    )
    schema_editor.execute(CURRENT_FUNCTION_SQL)


def disable_audit_event_hash_profiles(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(LEGACY_FUNCTION_SQL)
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_audithead ALTER COLUMN chain_head "
        "SET DEFAULT '0000000000000000000000000000000000000000000000000000000000000000'"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditcheckpoint ALTER COLUMN chain_head TYPE varchar(64)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditevent ALTER COLUMN event_hash TYPE varchar(64)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_auditevent ALTER COLUMN previous_hash TYPE varchar(64)"
    )
    schema_editor.execute(
        "ALTER TABLE budget_audit.audit_audithead ALTER COLUMN chain_head TYPE varchar(64)"
    )


class Migration(migrations.Migration):
    dependencies = [("audit", "0005_checkpoint_mac_profiles")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    enable_audit_event_hash_profiles,
                    disable_audit_event_hash_profiles,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="auditcheckpoint",
                    name="chain_head",
                    field=models.CharField(max_length=71),
                ),
                migrations.AlterField(
                    model_name="auditevent",
                    name="event_hash",
                    field=models.CharField(max_length=71),
                ),
                migrations.AlterField(
                    model_name="auditevent",
                    name="previous_hash",
                    field=models.CharField(max_length=71),
                ),
                migrations.AlterField(
                    model_name="audithead",
                    name="chain_head",
                    field=models.CharField(default=("sha256$" + "0" * 64), max_length=71),
                ),
            ],
        )
    ]
