# Generated by Django 5.2.17 on 2026-08-23 02:36

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "color",
                    models.CharField(
                        default="#64748B",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use a six-digit hex color."
                            )
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("is_archived", "sort_order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        models.F("household"),
                        django.db.models.functions.text.Lower("name"),
                        name="households_category_hh_name_ci_unique",
                    )
                ],
            },
        ),
    ]
