# Generated by Django 5.2.17 on 2026-08-23 12:30

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0002_postgresql_protect_history"),
        ("periods", "0002_postgresql_period_guards"),
        ("schedules", "0003_occurrence_schedules_occurrence_actual_nonnegative"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_occurrence_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_reconciliations",
                        to="households.household",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_reconciliations",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="schedules.occurrence",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["household", "created_at"], name="budgets_reconcile_hh_created"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("occurrence", "journal_entry"),
                        name="budgets_reconciliation_occ_entry_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0"))),
                        name="budgets_reconciliation_amount_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VariableBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("planned_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variable_budgets",
                        to="households.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_variable_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variable_budgets",
                        to="periods.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("category__sort_order", "category__name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pay_period", "category"),
                        name="budgets_variable_period_category_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("planned_amount__gte", Decimal("0"))),
                        name="budgets_variable_amount_nonnegative",
                    ),
                ],
            },
        ),
    ]
