# Generated by Django 5.2.17 on 2026-08-23 03:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        ("periods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReserveEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("period_close", "Period close"),
                            ("period_correction", "Closed-period correction"),
                            ("explicit_allocation", "Future explicit allocation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closing_revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reserve_entry",
                        to="periods.payperiodclosingrevision",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reserve_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reserve_entries",
                        to="households.household",
                    ),
                ),
                (
                    "posting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_reserve_entries",
                        to="periods.payperiod",
                    ),
                ),
                (
                    "source_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_reserve_entries",
                        to="periods.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["household", "created_at"], name="reserves_entry_hh_created"
                    )
                ],
            },
        ),
    ]
