# Generated by Django 5.2.17 on 2026-08-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_category"),
        ("periods", "0002_postgresql_period_guards"),
        ("reserves", "0002_postgresql_protect_entries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reserveentry",
            name="allocation_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="reserveentry",
            name="closing_revision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reserve_entry",
                to="periods.payperiodclosingrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="reserveentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allocation_label", ""),
                        ("closing_revision__isnull", False),
                        ("entry_type__in", ("period_close", "period_correction")),
                    ),
                    models.Q(
                        ("amount__lt", 0),
                        ("closing_revision__isnull", True),
                        ("entry_type", "explicit_allocation"),
                    ),
                    _connector="OR",
                ),
                name="reserves_entry_type_fields_valid",
            ),
        ),
    ]
