# Generated by Django 5.2.17 on 2026-08-23 17:18

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

PROTECT_CARD_RESERVE_SQL = r"""
DROP TRIGGER IF EXISTS card_reserve_entry_reject_mutation
    ON public.reserves_cardpaymentreserveentry;
CREATE TRIGGER card_reserve_entry_reject_mutation
BEFORE UPDATE OR DELETE ON public.reserves_cardpaymentreserveentry
FOR EACH ROW EXECUTE FUNCTION public.reject_reserve_entry_mutation();
DROP TRIGGER IF EXISTS card_reserve_entry_reject_truncate
    ON public.reserves_cardpaymentreserveentry;
CREATE TRIGGER card_reserve_entry_reject_truncate
BEFORE TRUNCATE ON public.reserves_cardpaymentreserveentry
FOR EACH STATEMENT EXECUTE FUNCTION public.reject_reserve_entry_mutation();
"""

UNPROTECT_CARD_RESERVE_SQL = r"""
DROP TRIGGER IF EXISTS card_reserve_entry_reject_mutation
    ON public.reserves_cardpaymentreserveentry;
DROP TRIGGER IF EXISTS card_reserve_entry_reject_truncate
    ON public.reserves_cardpaymentreserveentry;
"""


def protect_card_reserve_entries(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(PROTECT_CARD_RESERVE_SQL)


def unprotect_card_reserve_entries(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(UNPROTECT_CARD_RESERVE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0002_postgresql_protect_history"),
        ("periods", "0002_postgresql_period_guards"),
        ("reserves", "0003_reserveentry_allocation_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPaymentReserveEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Categorized purchase"),
                            ("purchase_reversal", "Purchase refund or reversal"),
                            ("payment", "Card payment allocation"),
                            ("payment_reversal", "Card payment reversal"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "reserve_settlement",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "debt_payoff",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                (
                    "neutral_correction",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_reserve_entries",
                        to="ledger.financialaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_card_payment_reserve_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_payment_reserve_entries",
                        to="households.household",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_payment_reserve_entry",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_payment_reserve_entries",
                        to="periods.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["card_account", "created_at"], name="reserves_card_account_time"
                    ),
                    models.Index(
                        fields=["household", "pay_period"], name="reserves_card_hh_period"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_amount__gte", Decimal("0.00")),
                            ("reserve_settlement__gte", Decimal("0.00")),
                            ("debt_payoff__gte", Decimal("0.00")),
                            ("neutral_correction__gte", Decimal("0.00")),
                        ),
                        name="reserves_card_amounts_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("amount__gt", Decimal("0.00")),
                                ("debt_payoff", Decimal("0.00")),
                                ("entry_type", "purchase"),
                                ("neutral_correction", Decimal("0.00")),
                                ("payment_amount", Decimal("0.00")),
                                ("reserve_settlement", Decimal("0.00")),
                            ),
                            models.Q(
                                ("amount__lte", Decimal("0.00")),
                                ("debt_payoff", Decimal("0.00")),
                                ("entry_type", "purchase_reversal"),
                                ("neutral_correction", Decimal("0.00")),
                                ("payment_amount", Decimal("0.00")),
                                ("reserve_settlement", Decimal("0.00")),
                            ),
                            models.Q(
                                (
                                    "amount",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("reserve_settlement"), "*", models.Value(-1)
                                    ),
                                ),
                                ("entry_type", "payment"),
                                ("neutral_correction", Decimal("0.00")),
                                (
                                    "payment_amount",
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("reserve_settlement"),
                                            "+",
                                            models.F("debt_payoff"),
                                        ),
                                        "+",
                                        models.F("neutral_correction"),
                                    ),
                                ),
                                ("payment_amount__gt", Decimal("0.00")),
                            ),
                            models.Q(
                                ("amount", models.F("reserve_settlement")),
                                ("entry_type", "payment_reversal"),
                                (
                                    "payment_amount",
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("reserve_settlement"),
                                            "+",
                                            models.F("debt_payoff"),
                                        ),
                                        "+",
                                        models.F("neutral_correction"),
                                    ),
                                ),
                                ("payment_amount__gt", Decimal("0.00")),
                            ),
                            _connector="OR",
                        ),
                        name="reserves_card_entry_type_amounts_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect_card_reserve_entries, unprotect_card_reserve_entries),
    ]
