# Generated by Django 5.2.17 on 2026-08-23 17:36

from decimal import Decimal

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum


def backfill_purchase_refund_amount(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    reserve_entry = apps.get_model("reserves", "CardPaymentReserveEntry")
    journal_posting = apps.get_model("ledger", "JournalPosting")
    entries = reserve_entry.objects.filter(
        entry_type="purchase_reversal",
        purchase_refund_amount=Decimal("0.00"),
    )
    for entry in entries.iterator():
        refund_amount = journal_posting.objects.filter(
            entry_id=entry.journal_entry_id,
            side="debit",
        ).aggregate(total=Sum("amount"))["total"]
        if refund_amount is not None:
            reserve_entry.objects.filter(pk=entry.pk).update(purchase_refund_amount=refund_amount)


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_category"),
        ("ledger", "0003_remove_journalentry_ledger_expense_category_required_and_more"),
        ("periods", "0002_postgresql_period_guards"),
        ("reserves", "0004_cardpaymentreserveentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cardpaymentreserveentry",
            name="reserves_card_amounts_nonnegative",
        ),
        migrations.RemoveConstraint(
            model_name="cardpaymentreserveentry",
            name="reserves_card_entry_type_amounts_valid",
        ),
        migrations.AddField(
            model_name="cardpaymentreserveentry",
            name="purchase_refund_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
        ),
        migrations.RunPython(backfill_purchase_refund_amount, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cardpaymentreserveentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_amount__gte", Decimal("0.00")),
                    ("reserve_settlement__gte", Decimal("0.00")),
                    ("debt_payoff__gte", Decimal("0.00")),
                    ("purchase_refund_amount__gte", Decimal("0.00")),
                    ("neutral_correction__gte", Decimal("0.00")),
                ),
                name="reserves_card_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardpaymentreserveentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount__gt", Decimal("0.00")),
                        ("debt_payoff", Decimal("0.00")),
                        ("entry_type", "purchase"),
                        ("neutral_correction", Decimal("0.00")),
                        ("payment_amount", Decimal("0.00")),
                        ("purchase_refund_amount", Decimal("0.00")),
                        ("reserve_settlement", Decimal("0.00")),
                    ),
                    models.Q(
                        ("amount__lte", Decimal("0.00")),
                        ("debt_payoff", Decimal("0.00")),
                        ("entry_type", "purchase_reversal"),
                        ("neutral_correction", Decimal("0.00")),
                        ("payment_amount", Decimal("0.00")),
                        ("purchase_refund_amount__gt", Decimal("0.00")),
                        ("reserve_settlement", Decimal("0.00")),
                    ),
                    models.Q(
                        (
                            "amount",
                            django.db.models.expressions.CombinedExpression(
                                models.F("reserve_settlement"), "*", models.Value(-1)
                            ),
                        ),
                        ("entry_type", "payment"),
                        ("neutral_correction", Decimal("0.00")),
                        (
                            "payment_amount",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("reserve_settlement"), "+", models.F("debt_payoff")
                                ),
                                "+",
                                models.F("neutral_correction"),
                            ),
                        ),
                        ("payment_amount__gt", Decimal("0.00")),
                        ("purchase_refund_amount", Decimal("0.00")),
                    ),
                    models.Q(
                        ("amount", models.F("reserve_settlement")),
                        ("entry_type", "payment_reversal"),
                        (
                            "payment_amount",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("reserve_settlement"), "+", models.F("debt_payoff")
                                ),
                                "+",
                                models.F("neutral_correction"),
                            ),
                        ),
                        ("payment_amount__gt", Decimal("0.00")),
                        ("purchase_refund_amount", Decimal("0.00")),
                    ),
                    _connector="OR",
                ),
                name="reserves_card_entry_type_amounts_valid",
            ),
        ),
    ]
