# Generated by Django 5.2.17 on 2026-08-23 03:14

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import schedules.recurrence


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        ("periods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("fixed_expense", "Fixed expense"),
                            ("debt_payment", "Debt payment"),
                            ("goal_contribution", "Goal contribution"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("archived_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_recurring_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_sources",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ("archived_at", "kind", "name"),
            },
        ),
        migrations.CreateModel(
            name="IncomeSourceDetail",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="income_detail",
                        serialize=False,
                        to="schedules.recurringsource",
                    ),
                ),
                ("starts_budget_period", models.BooleanField(default=True)),
                ("is_variable", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SourceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("expected_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly_day", "Monthly Day"),
                            ("monthly_nth_weekday", "Monthly Nth Weekday"),
                            ("monthly_last_weekday", "Monthly Last Weekday"),
                            ("annual", "Annual"),
                        ],
                        max_length=28,
                    ),
                ),
                ("interval", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("weekdays", models.JSONField(blank=True, default=list)),
                ("day_of_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ordinal", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month_of_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "adjustment_policy",
                    models.CharField(
                        choices=[("none", "None"), ("previous", "Previous"), ("next", "Next")],
                        default=schedules.recurrence.BusinessDayAdjustment["PREVIOUS"],
                        max_length=12,
                    ),
                ),
                ("holiday_dates", models.JSONField(blank=True, default=list)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_source_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="schedules.recurringsource",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "revision_number"),
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nominal_date", models.DateField()),
                ("generated_expected_date", models.DateField()),
                ("expected_date", models.DateField()),
                ("generated_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("planned_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("moved", "Moved"),
                            ("overridden", "Overridden"),
                            ("completed", "Completed"),
                            ("corrected", "Corrected"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Superseded by schedule revision"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("override_reason", models.CharField(blank=True, max_length=500)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moved_from_occurrences",
                        to="periods.payperiod",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="periods.payperiod",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="schedules.recurringsource",
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="schedules.sourcerevision",
                    ),
                ),
            ],
            options={
                "ordering": ("expected_date", "source__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="recurringsource",
            constraint=models.UniqueConstraint(
                models.F("household"),
                models.F("kind"),
                django.db.models.functions.text.Lower("name"),
                name="schedules_source_hh_kind_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.UniqueConstraint(
                fields=("source", "revision_number"), name="schedules_revision_source_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.UniqueConstraint(
                fields=("source", "effective_from"),
                name="schedules_revision_source_effective_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_amount__gte", Decimal("0"))),
                name="schedules_revision_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="schedules_revision_date_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__gte", models.F("effective_from"))),
                name="schedules_revision_start_after_effective",
            ),
        ),
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(
                fields=["source", "expected_date"], name="schedules_occ_source_date"
            ),
        ),
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(fields=["pay_period", "status"], name="schedules_occ_period_status"),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.UniqueConstraint(
                fields=("source_revision", "nominal_date"),
                name="schedules_occurrence_revision_nominal_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("generated_amount__gte", Decimal("0"))),
                name="schedules_occurrence_generated_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_amount__gte", Decimal("0"))),
                name="schedules_occurrence_planned_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pay_period__isnull", False),
                    ("status__in", ("cancelled", "superseded")),
                    _connector="OR",
                ),
                name="schedules_active_occurrence_has_period",
            ),
        ),
    ]
