# Generated by Django 5.2.17 on 2026-08-23 03:20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periods", "0002_postgresql_period_guards"),
        ("schedules", "0002_postgresql_protect_revisions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="occurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_amount__isnull", True),
                    ("actual_amount__gte", Decimal("0")),
                    _connector="OR",
                ),
                name="schedules_occurrence_actual_nonnegative",
            ),
        ),
    ]
