# Generated by Django 5.2.17 on 2026-08-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_category"),
        ("schedules", "0003_occurrence_schedules_occurrence_actual_nonnegative"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSourceDetail",
            fields=[
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="expense_detail",
                        serialize=False,
                        to="schedules.recurringsource",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_expense_sources",
                        to="households.category",
                    ),
                ),
            ],
        ),
    ]
