# Generated by Django 5.2.17 on 2026-08-24 13:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0003_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("due_soon", "Upcoming bill"),
                            ("overdue", "Overdue bill"),
                            ("missing_income", "Missing paycheck"),
                            ("deficit", "Projected deficit"),
                            ("goal_milestone", "Goal milestone"),
                            ("backup", "Backup"),
                            ("login_activity", "Login activity"),
                            ("integrity", "Audit integrity"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=160)),
                ("message", models.CharField(max_length=500)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("source_type", models.CharField(max_length=80)),
                ("source_id", models.CharField(max_length=80)),
                ("occurred_at", models.DateTimeField()),
                ("last_evaluated_at", models.DateTimeField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="households.household",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["household", "recipient", "dismissed_at", "resolved_at"],
                        name="notifications_recipient_state",
                    ),
                    models.Index(
                        fields=["household", "kind", "source_type", "source_id"],
                        name="notifications_source_lookup",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "recipient", "fingerprint"),
                        name="notifications_hh_recipient_fingerprint_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("due_alerts", models.BooleanField(default=True)),
                ("missing_income_alerts", models.BooleanField(default=True)),
                ("deficit_alerts", models.BooleanField(default=True)),
                ("goal_alerts", models.BooleanField(default=True)),
                ("backup_alerts", models.BooleanField(default=True)),
                ("login_alerts", models.BooleanField(default=True)),
                ("integrity_alerts", models.BooleanField(default=True)),
                ("upcoming_due_days", models.PositiveSmallIntegerField(default=3)),
                ("missing_income_grace_days", models.PositiveSmallIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="households.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "user"), name="notifications_preference_hh_user_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("upcoming_due_days__lte", 30)),
                        name="notifications_preference_due_days_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("missing_income_grace_days__lte", 30)),
                        name="notifications_preference_income_grace_max",
                    ),
                ],
            },
        ),
    ]
