# Generated by Django 5.2.17 on 2026-09-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="fingerprint",
            field=models.CharField(max_length=71),
        ),
    ]
